//
//  CoffeeApp.swift
//  iOS Module
//
//  Created by Andreas Gasser on 08/03/17.
//  Copyright © 2017 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class CoffeeCapsule : NSObject {

    //// Drawing Methods

    public dynamic class func drawCoffeeCapsule(frame: CGRect = CGRect(x: 19, y: 18, width: 86, height: 87), color: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)) {


        //// Subframes
        let capsule: CGRect = CGRect(x: frame.minX + 6.5, y: frame.minY + 7.5, width: frame.width - 11, height: frame.height - 12)


        //// Capsule
        //// Body Drawing
        let bodyPath = UIBezierPath()
        bodyPath.move(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.87600 * capsule.height))
        bodyPath.addCurve(to: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.72400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.69600 * capsule.width, y: capsule.minY + 0.87600 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.80667 * capsule.height))
        bodyPath.addCurve(to: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.71867 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.72267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.72133 * capsule.height))
        bodyPath.addLine(to: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.71733 * capsule.height))
        bodyPath.addLine(to: CGPoint(x: capsule.minX + 0.86133 * capsule.width, y: capsule.minY + 0.71600 * capsule.height))
        bodyPath.addLine(to: CGPoint(x: capsule.minX + 0.78667 * capsule.width, y: capsule.minY + 0.25200 * capsule.height))
        bodyPath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.34667 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.74533 * capsule.width, y: capsule.minY + 0.30800 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.63333 * capsule.width, y: capsule.minY + 0.34667 * capsule.height))
        bodyPath.addCurve(to: CGPoint(x: capsule.minX + 0.21333 * capsule.width, y: capsule.minY + 0.25467 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.36667 * capsule.width, y: capsule.minY + 0.34667 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.25600 * capsule.width, y: capsule.minY + 0.30933 * capsule.height))
        bodyPath.addLine(to: CGPoint(x: capsule.minX + 0.13867 * capsule.width, y: capsule.minY + 0.72000 * capsule.height))
        bodyPath.addLine(to: CGPoint(x: capsule.minX + 0.13867 * capsule.width, y: capsule.minY + 0.72000 * capsule.height))
        bodyPath.addCurve(to: CGPoint(x: capsule.minX + 0.13867 * capsule.width, y: capsule.minY + 0.72400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.13867 * capsule.width, y: capsule.minY + 0.72133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.13867 * capsule.width, y: capsule.minY + 0.72267 * capsule.height))
        bodyPath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.87600 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.13867 * capsule.width, y: capsule.minY + 0.80667 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.30400 * capsule.width, y: capsule.minY + 0.87600 * capsule.height))
        bodyPath.close()
        color.setFill()
        bodyPath.fill()


        //// Neck Drawing
        let neckPath = UIBezierPath()
        neckPath.move(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.14000 * capsule.height))
        neckPath.addCurve(to: CGPoint(x: capsule.minX + 0.60000 * capsule.width, y: capsule.minY + 0.10267 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.56133 * capsule.width, y: capsule.minY + 0.14000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.60000 * capsule.width, y: capsule.minY + 0.11867 * capsule.height))
        neckPath.addCurve(to: CGPoint(x: capsule.minX + 0.56400 * capsule.width, y: capsule.minY + 0.07600 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.60000 * capsule.width, y: capsule.minY + 0.09467 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.58667 * capsule.width, y: capsule.minY + 0.08267 * capsule.height))
        neckPath.addCurve(to: CGPoint(x: capsule.minX + 0.43067 * capsule.width, y: capsule.minY + 0.07733 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.52533 * capsule.width, y: capsule.minY + 0.06267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.46800 * capsule.width, y: capsule.minY + 0.06400 * capsule.height))
        neckPath.addCurve(to: CGPoint(x: capsule.minX + 0.39867 * capsule.width, y: capsule.minY + 0.10400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.40933 * capsule.width, y: capsule.minY + 0.08533 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.39867 * capsule.width, y: capsule.minY + 0.09467 * capsule.height))
        neckPath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.14000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.40000 * capsule.width, y: capsule.minY + 0.11867 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.43867 * capsule.width, y: capsule.minY + 0.14000 * capsule.height))
        neckPath.close()
        color.setFill()
        neckPath.fill()


        //// Shoulder Drawing
        let shoulderPath = UIBezierPath()
        shoulderPath.move(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.32000 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.77867 * capsule.width, y: capsule.minY + 0.20400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.66667 * capsule.width, y: capsule.minY + 0.32000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.77867 * capsule.width, y: capsule.minY + 0.26000 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.67067 * capsule.width, y: capsule.minY + 0.11333 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.77867 * capsule.width, y: capsule.minY + 0.16933 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.73867 * capsule.width, y: capsule.minY + 0.13600 * capsule.height))
        shoulderPath.addLine(to: CGPoint(x: capsule.minX + 0.67067 * capsule.width, y: capsule.minY + 0.11333 * capsule.height))
        shoulderPath.addLine(to: CGPoint(x: capsule.minX + 0.62667 * capsule.width, y: capsule.minY + 0.09867 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.62667 * capsule.width, y: capsule.minY + 0.10400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.62667 * capsule.width, y: capsule.minY + 0.10000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.62667 * capsule.width, y: capsule.minY + 0.10267 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.49867 * capsule.width, y: capsule.minY + 0.16800 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.62667 * capsule.width, y: capsule.minY + 0.14000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.57200 * capsule.width, y: capsule.minY + 0.16800 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.37067 * capsule.width, y: capsule.minY + 0.10400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.42667 * capsule.width, y: capsule.minY + 0.16800 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.37067 * capsule.width, y: capsule.minY + 0.14000 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.37067 * capsule.width, y: capsule.minY + 0.09867 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.37067 * capsule.width, y: capsule.minY + 0.10267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.37067 * capsule.width, y: capsule.minY + 0.10000 * capsule.height))
        shoulderPath.addLine(to: CGPoint(x: capsule.minX + 0.33067 * capsule.width, y: capsule.minY + 0.11200 * capsule.height))
        shoulderPath.addLine(to: CGPoint(x: capsule.minX + 0.33067 * capsule.width, y: capsule.minY + 0.11200 * capsule.height))
        shoulderPath.addLine(to: CGPoint(x: capsule.minX + 0.33067 * capsule.width, y: capsule.minY + 0.11200 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.21867 * capsule.width, y: capsule.minY + 0.20400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.26133 * capsule.width, y: capsule.minY + 0.13467 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.21867 * capsule.width, y: capsule.minY + 0.16800 * capsule.height))
        shoulderPath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.32000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.22133 * capsule.width, y: capsule.minY + 0.26000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.33333 * capsule.width, y: capsule.minY + 0.32000 * capsule.height))
        shoulderPath.close()
        color.setFill()
        shoulderPath.fill()


        //// Outline Drawing
        let outlinePath = UIBezierPath()
        outlinePath.move(to: CGPoint(x: capsule.minX + 0.90533 * capsule.width, y: capsule.minY + 0.56800 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.84533 * capsule.width, y: capsule.minY + 0.19067 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.69200 * capsule.width, y: capsule.minY + 0.04933 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.83867 * capsule.width, y: capsule.minY + 0.12933 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.78400 * capsule.width, y: capsule.minY + 0.08000 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58933 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58933 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58933 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58933 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58933 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58800 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.58667 * capsule.width, y: capsule.minY + 0.01333 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.56800 * capsule.width, y: capsule.minY + 0.00800 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.58133 * capsule.width, y: capsule.minY + 0.01200 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.57467 * capsule.width, y: capsule.minY + 0.00933 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.56667 * capsule.width, y: capsule.minY + 0.00800 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.52533 * capsule.width, y: capsule.minY + 0.00133 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.55333 * capsule.width, y: capsule.minY + 0.00533 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.54000 * capsule.width, y: capsule.minY + 0.00267 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.52133 * capsule.width, y: capsule.minY + 0.00133 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.00000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.51333 * capsule.width, y: capsule.minY + 0.00133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.50667 * capsule.width, y: capsule.minY + 0.00000 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.47733 * capsule.width, y: capsule.minY + 0.00133 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.49333 * capsule.width, y: capsule.minY + 0.00000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.48533 * capsule.width, y: capsule.minY + 0.00000 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.47600 * capsule.width, y: capsule.minY + 0.00133 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.47467 * capsule.width, y: capsule.minY + 0.00133 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.41067 * capsule.width, y: capsule.minY + 0.01467 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.45200 * capsule.width, y: capsule.minY + 0.00267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.42933 * capsule.width, y: capsule.minY + 0.00800 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.40933 * capsule.width, y: capsule.minY + 0.01467 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.40933 * capsule.width, y: capsule.minY + 0.01467 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.31067 * capsule.width, y: capsule.minY + 0.04933 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.15333 * capsule.width, y: capsule.minY + 0.20267 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.21200 * capsule.width, y: capsule.minY + 0.08133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.15467 * capsule.width, y: capsule.minY + 0.13733 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.09467 * capsule.width, y: capsule.minY + 0.56800 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.00000 * capsule.width, y: capsule.minY + 0.72933 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.01600 * capsule.width, y: capsule.minY + 0.62533 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.00000 * capsule.width, y: capsule.minY + 0.68667 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 1.00000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.00000 * capsule.width, y: capsule.minY + 0.88267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.21467 * capsule.width, y: capsule.minY + 1.00000 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 1.00000 * capsule.width, y: capsule.minY + 0.72933 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.78533 * capsule.width, y: capsule.minY + 1.00000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 1.00000 * capsule.width, y: capsule.minY + 0.88400 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.90533 * capsule.width, y: capsule.minY + 0.56800 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 1.00000 * capsule.width, y: capsule.minY + 0.68667 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.98267 * capsule.width, y: capsule.minY + 0.62533 * capsule.height))
        outlinePath.close()
        outlinePath.move(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.96000 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.04000 * capsule.width, y: capsule.minY + 0.72933 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.24267 * capsule.width, y: capsule.minY + 0.96000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.04000 * capsule.width, y: capsule.minY + 0.85867 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.13200 * capsule.width, y: capsule.minY + 0.59067 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.04000 * capsule.width, y: capsule.minY + 0.67867 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.07200 * capsule.width, y: capsule.minY + 0.63067 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.19467 * capsule.width, y: capsule.minY + 0.20533 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.19467 * capsule.width, y: capsule.minY + 0.20400 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.32400 * capsule.width, y: capsule.minY + 0.08667 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.19467 * capsule.width, y: capsule.minY + 0.15600 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.24133 * capsule.width, y: capsule.minY + 0.11333 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.32400 * capsule.width, y: capsule.minY + 0.08667 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.42267 * capsule.width, y: capsule.minY + 0.05200 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.42400 * capsule.width, y: capsule.minY + 0.05200 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.47867 * capsule.width, y: capsule.minY + 0.04133 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.44000 * capsule.width, y: capsule.minY + 0.04667 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.45867 * capsule.width, y: capsule.minY + 0.04267 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.48133 * capsule.width, y: capsule.minY + 0.04133 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.48000 * capsule.width, y: capsule.minY + 0.04133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.48000 * capsule.width, y: capsule.minY + 0.04133 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.50133 * capsule.width, y: capsule.minY + 0.04000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.48800 * capsule.width, y: capsule.minY + 0.04133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.49467 * capsule.width, y: capsule.minY + 0.04000 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.52000 * capsule.width, y: capsule.minY + 0.04000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.50800 * capsule.width, y: capsule.minY + 0.04000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.51333 * capsule.width, y: capsule.minY + 0.04000 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.52400 * capsule.width, y: capsule.minY + 0.04000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.52133 * capsule.width, y: capsule.minY + 0.04000 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.52267 * capsule.width, y: capsule.minY + 0.04000 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.55867 * capsule.width, y: capsule.minY + 0.04533 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.53600 * capsule.width, y: capsule.minY + 0.04133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.54800 * capsule.width, y: capsule.minY + 0.04267 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.56000 * capsule.width, y: capsule.minY + 0.04533 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.57600 * capsule.width, y: capsule.minY + 0.04933 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.56533 * capsule.width, y: capsule.minY + 0.04667 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.57067 * capsule.width, y: capsule.minY + 0.04800 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.57600 * capsule.width, y: capsule.minY + 0.04933 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.57600 * capsule.width, y: capsule.minY + 0.04933 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.57600 * capsule.width, y: capsule.minY + 0.04933 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.68000 * capsule.width, y: capsule.minY + 0.08533 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.80667 * capsule.width, y: capsule.minY + 0.19467 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.75600 * capsule.width, y: capsule.minY + 0.11067 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.80133 * capsule.width, y: capsule.minY + 0.14933 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.80667 * capsule.width, y: capsule.minY + 0.19467 * capsule.height))
        outlinePath.addLine(to: CGPoint(x: capsule.minX + 0.86933 * capsule.width, y: capsule.minY + 0.58933 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.96133 * capsule.width, y: capsule.minY + 0.72800 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.92933 * capsule.width, y: capsule.minY + 0.62933 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.96133 * capsule.width, y: capsule.minY + 0.67733 * capsule.height))
        outlinePath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.96000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.96000 * capsule.width, y: capsule.minY + 0.85867 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.75733 * capsule.width, y: capsule.minY + 0.96000 * capsule.height))
        outlinePath.close()
        color.setFill()
        outlinePath.fill()


        //// Border Drawing
        let borderPath = UIBezierPath()
        borderPath.move(to: CGPoint(x: capsule.minX + 0.87467 * capsule.width, y: capsule.minY + 0.62933 * capsule.height))
        borderPath.addLine(to: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71333 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71600 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71467 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71467 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71867 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71733 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.71733 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.72533 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.72133 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.72267 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.50000 * capsule.width, y: capsule.minY + 0.90400 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.88800 * capsule.width, y: capsule.minY + 0.82533 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.71733 * capsule.width, y: capsule.minY + 0.90400 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.72533 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.28267 * capsule.width, y: capsule.minY + 0.90400 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.82533 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.72000 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.72267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.72133 * capsule.height))
        borderPath.addLine(to: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.72000 * capsule.height))
        borderPath.addLine(to: CGPoint(x: capsule.minX + 0.11200 * capsule.width, y: capsule.minY + 0.71867 * capsule.height))
        borderPath.addLine(to: CGPoint(x: capsule.minX + 0.12667 * capsule.width, y: capsule.minY + 0.62933 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.06800 * capsule.width, y: capsule.minY + 0.73067 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.09600 * capsule.width, y: capsule.minY + 0.65333 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.06800 * capsule.width, y: capsule.minY + 0.68800 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.50133 * capsule.width, y: capsule.minY + 0.93333 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.06800 * capsule.width, y: capsule.minY + 0.84267 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.26267 * capsule.width, y: capsule.minY + 0.93333 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.93467 * capsule.width, y: capsule.minY + 0.73067 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.74000 * capsule.width, y: capsule.minY + 0.93333 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.93467 * capsule.width, y: capsule.minY + 0.84267 * capsule.height))
        borderPath.addCurve(to: CGPoint(x: capsule.minX + 0.87467 * capsule.width, y: capsule.minY + 0.62933 * capsule.height), controlPoint1: CGPoint(x: capsule.minX + 0.93333 * capsule.width, y: capsule.minY + 0.68800 * capsule.height), controlPoint2: CGPoint(x: capsule.minX + 0.90533 * capsule.width, y: capsule.minY + 0.65333 * capsule.height))
        borderPath.close()
        color.setFill()
        borderPath.fill()
    }

}
